const SEMAPHORE_PROOF_COMPONENTS = [
  { name: "merkleTreeDepth", type: "uint256" },
  { name: "merkleTreeRoot", type: "uint256" },
  { name: "nullifier", type: "uint256" },
  { name: "message", type: "uint256" },
  { name: "scope", type: "uint256" },
  { name: "points", type: "uint256[8]" },
] as const;

export const CONTENT_REGISTRY_ABI = [
  {
    type: "function",
    name: "contentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "contents",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "author", type: "address" },
      { name: "ownerTag", type: "bytes32" },
      { name: "canonicalTag", type: "bytes32" },
      { name: "moderatorTag", type: "bytes32" },
      { name: "contentHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "version", type: "uint64" },
      { name: "exists", type: "bool" },
      { name: "revoked", type: "bool" },
      { name: "moderated", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "editVerifier",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "semaphore",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "groupId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "post",
    stateMutability: "nonpayable",
    inputs: [
      { name: "proof", type: "tuple", components: SEMAPHORE_PROOF_COMPONENTS },
      { name: "contentHash", type: "bytes32" },
      { name: "ownerTag", type: "bytes32" },
      { name: "canonicalTag", type: "bytes32" },
      { name: "moderatorTag", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "postPublic",
    stateMutability: "nonpayable",
    inputs: [
      { name: "contentHash", type: "bytes32" },
      { name: "canonicalTag", type: "bytes32" },
      { name: "moderatorTag", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "removePublic",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "update",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "proof", type: "bytes" },
      { name: "newContentHash", type: "bytes32" },
      { name: "nonce", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "moderate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "proof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "Posted",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "author", type: "address", indexed: false },
      { name: "ownerTag", type: "bytes32", indexed: false },
      { name: "canonicalTag", type: "bytes32", indexed: false },
      { name: "moderatorTag", type: "bytes32", indexed: false },
      { name: "contentHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Updated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "contentHash", type: "bytes32", indexed: false },
      { name: "version", type: "uint64", indexed: false },
      { name: "revoked", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Moderated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "canonicalTag", type: "bytes32", indexed: false },
    ],
  },
  { type: "error", name: "BadScope", inputs: [] },
  { type: "error", name: "BadProof", inputs: [] },
  { type: "error", name: "NoContent", inputs: [] },
  { type: "error", name: "AlreadyRevoked", inputs: [] },
  { type: "error", name: "BadNonce", inputs: [] },
  { type: "error", name: "NoCanonical", inputs: [] },
] as const;
