export const CYBERSWAGMAN_REGISTRY_ABI = [
  {
    type: "function",
    name: "agentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "agents",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "modelHash", type: "bytes32" },
      { name: "hardwareHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "inSchema",
    stateMutability: "view",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "kitId", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "result",
    stateMutability: "view",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "projectId", type: "uint256" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "registerAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "modelHash", type: "bytes32" },
      { name: "hardwareHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "agentId", type: "uint256" }],
  },
  {
    type: "function",
    name: "registerAgentWithKits",
    stateMutability: "nonpayable",
    inputs: [
      { name: "modelHash", type: "bytes32" },
      { name: "hardwareHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "kitIds", type: "uint256[]" },
    ],
    outputs: [{ name: "agentId", type: "uint256" }],
  },
  {
    type: "function",
    name: "updateAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "modelHash", type: "bytes32" },
      { name: "hardwareHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "addKits", type: "uint256[]" },
      { name: "removeKits", type: "uint256[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setSchema",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "kitId", type: "uint256" },
      { name: "included", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "postResult",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "projectId", type: "uint256" },
      { name: "resultHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deleteAgent",
    stateMutability: "nonpayable",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "event",
    name: "AgentRegistered",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "modelHash", type: "bytes32", indexed: false },
      { name: "hardwareHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ResultPosted",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "projectId", type: "uint256", indexed: true },
      { name: "resultHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
    ],
  },
  { type: "error", name: "NoAgent", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "NoKits", inputs: [] },
  { type: "error", name: "Banned", inputs: [] },
] as const;
