const SEMAPHORE_PROOF_COMPONENTS = [
  { name: "merkleTreeDepth", type: "uint256" },
  { name: "merkleTreeRoot", type: "uint256" },
  { name: "nullifier", type: "uint256" },
  { name: "message", type: "uint256" },
  { name: "scope", type: "uint256" },
  { name: "points", type: "uint256[8]" },
] as const;

export const DX_COUNCIL_ABI = [
  {
    type: "function",
    name: "proposalCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "proposals",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "identityRoot", type: "uint256" },
      { name: "balanceRoot", type: "bytes32" },
      { name: "start", type: "uint64" },
      { name: "end", type: "uint64" },
      { name: "exists", type: "bool" },
      { name: "executed", type: "bool" },
      { name: "kind", type: "uint8" },
      { name: "wallet", type: "address" },
      { name: "banned", type: "bool" },
      { name: "value", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "tally",
    stateMutability: "view",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "choice", type: "uint8" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "quorum",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "quorumFloor",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint128" }],
  },
  {
    type: "function",
    name: "proposeBan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "wallet", type: "address" },
      { name: "banned", type: "bool" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "proposeQuorum",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newQuorum", type: "uint256" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "proposeWindow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newWindow", type: "uint256" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "votingWindow",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint64" }],
  },
  {
    type: "function",
    name: "vote",
    stateMutability: "nonpayable",
    inputs: [
      { name: "voteProof", type: "tuple", components: SEMAPHORE_PROOF_COMPONENTS },
      { name: "balanceLinkProof", type: "tuple", components: SEMAPHORE_PROOF_COMPONENTS },
      { name: "balanceZkProof", type: "bytes" },
      { name: "proposalId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "execute",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "event",
    name: "ProposalCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "kind", type: "uint8", indexed: false },
      { name: "wallet", type: "address", indexed: true },
      { name: "banned", type: "bool", indexed: false },
      { name: "value", type: "uint256", indexed: false },
      { name: "end", type: "uint64", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Voted",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "choice", type: "uint8", indexed: false },
      { name: "nullifier", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Executed",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "kind", type: "uint8", indexed: false },
      { name: "wallet", type: "address", indexed: true },
    ],
  },
  { type: "error", name: "NoProposal", inputs: [] },
  { type: "error", name: "VotingClosed", inputs: [] },
  { type: "error", name: "VotingOpen", inputs: [] },
  { type: "error", name: "InvalidChoice", inputs: [] },
  { type: "error", name: "AlreadyExecuted", inputs: [] },
  { type: "error", name: "Rejected", inputs: [] },
  { type: "error", name: "BadProof", inputs: [] },
  { type: "error", name: "BadScope", inputs: [] },
  { type: "error", name: "StaleRoot", inputs: [] },
  { type: "error", name: "BelowFloor", inputs: [] },
  { type: "error", name: "BadWindow", inputs: [] },
] as const;
