export const GRANT_REGISTRY_ABI = [
  {
    type: "function",
    name: "grantCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "grants",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "kitId", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "purposeHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "budget", type: "uint256" },
      { name: "raised", type: "uint256" },
      { name: "totalShares", type: "uint256" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "shares",
    stateMutability: "view",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "funder", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pendingReward",
    stateMutability: "view",
    inputs: [
      { name: "grantId", type: "uint256" },
      { name: "funder", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSharesOf",
    stateMutability: "view",
    inputs: [{ name: "grantId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "ruggedCreator",
    stateMutability: "view",
    inputs: [{ name: "grantId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "blacklistRuggedCreator",
    stateMutability: "nonpayable",
    inputs: [{ name: "grantId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "createGrant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "kitId", type: "uint256" },
      { name: "purposeHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "budget", type: "uint256" },
    ],
    outputs: [{ name: "grantId", type: "uint256" }],
  },
  {
    type: "function",
    name: "updateGrant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "grantId", type: "uint256" },
      { name: "purposeHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "budget", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeGrant",
    stateMutability: "nonpayable",
    inputs: [{ name: "grantId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "fundGrant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "grantId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "notifyReward",
    stateMutability: "nonpayable",
    inputs: [
      { name: "grantId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ name: "grantId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setBlacklisted",
    stateMutability: "nonpayable",
    inputs: [
      { name: "creator", type: "address" },
      { name: "banned", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "GrantCreated",
    inputs: [
      { name: "grantId", type: "uint256", indexed: true },
      { name: "kitId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "purposeHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
      { name: "budget", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GrantUpdated",
    inputs: [
      { name: "grantId", type: "uint256", indexed: true },
      { name: "purposeHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
      { name: "budget", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GrantRemoved",
    inputs: [{ name: "grantId", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "GrantFunded",
    inputs: [
      { name: "grantId", type: "uint256", indexed: true },
      { name: "funder", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "totalFunderShares", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardAdded",
    inputs: [
      { name: "grantId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "grantId", type: "uint256", indexed: true },
      { name: "funder", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  { type: "error", name: "NoGrant", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "NoFunders", inputs: [] },
  { type: "error", name: "Banned", inputs: [] },
  { type: "error", name: "NotCouncil", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "NotCreator", inputs: [] },
  { type: "error", name: "HasFunders", inputs: [] },
  { type: "error", name: "NotRugged", inputs: [] },
  { type: "error", name: "NoShares", inputs: [] },
] as const;
