export const IDENTITY_REGISTRY_ABI = [
  {
    type: "function",
    name: "currentRoot",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "isKnownRoot",
    stateMutability: "view",
    inputs: [{ name: "candidate", type: "bytes32" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "enrolledCommitment",
    stateMutability: "view",
    inputs: [{ name: "commitment", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "enrollmentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint32" }],
  },
  {
    type: "function",
    name: "usedEnrollNullifier",
    stateMutability: "view",
    inputs: [{ name: "nullifier", type: "bytes32" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "enroll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "proof", type: "bytes" },
      { name: "freshBind", type: "bytes32" },
      { name: "enrollNullifier", type: "bytes32" },
      { name: "commitment", type: "uint256" },
      { name: "siblings", type: "bytes32[20]" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "event",
    name: "Enrolled",
    inputs: [
      { name: "commitment", type: "uint256", indexed: true },
      { name: "enrollNullifier", type: "bytes32", indexed: false },
      { name: "leafIndex", type: "uint32", indexed: false },
      { name: "root", type: "bytes32", indexed: false },
    ],
  },
  { type: "error", name: "AlreadyEnrolled", inputs: [] },
  { type: "error", name: "CommitmentExists", inputs: [] },
  { type: "error", name: "BadProof", inputs: [] },
  { type: "error", name: "TreeFull", inputs: [] },
  { type: "error", name: "StalePath", inputs: [] },
  { type: "error", name: "ZeroCommitment", inputs: [] },
] as const;
