export const KIT_REGISTRY_ABI = [
  {
    type: "function",
    name: "kitCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "kits",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "ownerTag", type: "bytes32" },
      { name: "designHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "parentId", type: "uint256" },
      { name: "version", type: "uint64" },
      { name: "exists", type: "bool" },
      { name: "revoked", type: "bool" },
      { name: "mode", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "transferFrom",
    stateMutability: "nonpayable",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "publishVerifier",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "editVerifier",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "roots",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "publishPublic",
    stateMutability: "nonpayable",
    inputs: [
      { name: "designHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "forkPublic",
    stateMutability: "nonpayable",
    inputs: [
      { name: "parentId", type: "uint256" },
      { name: "designHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "pushVersionPublic",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "newDesignHash", type: "bytes32" },
      { name: "newContentUri", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removePublic",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "publish",
    stateMutability: "nonpayable",
    inputs: [
      { name: "proof", type: "bytes" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "designHash", type: "bytes32" },
      { name: "ownerTag", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "fork",
    stateMutability: "nonpayable",
    inputs: [
      { name: "parentId", type: "uint256" },
      { name: "proof", type: "bytes" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "designHash", type: "bytes32" },
      { name: "ownerTag", type: "bytes32" },
      { name: "contentUri", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "pushVersion",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "ownerProof", type: "bytes" },
      { name: "actionProof", type: "bytes" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "newDesignHash", type: "bytes32" },
      { name: "nonce", type: "uint64" },
      { name: "newContentUri", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "remove",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "ownerProof", type: "bytes" },
      { name: "actionProof", type: "bytes" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "nonce", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "retag",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "ownerProof", type: "bytes" },
      { name: "actionProof", type: "bytes" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "newOwnerTag", type: "bytes32" },
      { name: "nonce", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "to", type: "address" },
      { name: "ownerProof", type: "bytes" },
      { name: "actionProof", type: "bytes" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "nonce", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "KitClaimed",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "KitPublished",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "parentId", type: "uint256", indexed: true },
      { name: "mode", type: "uint8", indexed: false },
      { name: "designHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "KitVersioned",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "designHash", type: "bytes32", indexed: false },
      { name: "version", type: "uint64", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "KitRemoved",
    inputs: [{ name: "id", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "KitRetagged",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "newOwnerTag", type: "bytes32", indexed: false },
    ],
  },
  { type: "error", name: "UnknownRoot", inputs: [] },
  { type: "error", name: "BadProof", inputs: [] },
  { type: "error", name: "NoKit", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "AlreadyRevoked", inputs: [] },
  { type: "error", name: "BadNonce", inputs: [] },
  { type: "error", name: "NoParent", inputs: [] },
  { type: "error", name: "WrongMode", inputs: [] },
] as const;
