export const MATROID_PAYMASTER_ABI = [
  {
    type: "function",
    name: "registered",
    stateMutability: "view",
    inputs: [{ name: "project", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "blacklisted",
    stateMutability: "view",
    inputs: [{ name: "project", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "capOf",
    stateMutability: "view",
    inputs: [{ name: "project", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "capPerEpoch",
    stateMutability: "view",
    inputs: [{ name: "project", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "defaultCapPerEpoch",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "currentEpoch",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "spentInEpoch",
    stateMutability: "view",
    inputs: [
      { name: "project", type: "address" },
      { name: "epoch", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "governance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "fund",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setRegistered",
    stateMutability: "nonpayable",
    inputs: [
      { name: "project", type: "address" },
      { name: "active", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setBlacklisted",
    stateMutability: "nonpayable",
    inputs: [
      { name: "project", type: "address" },
      { name: "banned", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "project", type: "address" },
      { name: "cap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "Registered",
    inputs: [
      { name: "project", type: "address", indexed: true },
      { name: "active", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Funded",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SponsoredCall",
    inputs: [
      { name: "project", type: "address", indexed: true },
      { name: "from", type: "address", indexed: true },
      { name: "fee", type: "uint256", indexed: false },
      { name: "epoch", type: "uint256", indexed: false },
    ],
  },
  { type: "error", name: "NotRegistered", inputs: [] },
  { type: "error", name: "ProjectBanned", inputs: [] },
  { type: "error", name: "OverEpochLimit", inputs: [] },
] as const;
