export const PREFAB_MARKET_ABI = [
  {
    type: "function",
    name: "offerCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "orderCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "offers",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "fabricator", type: "address" },
      { name: "kitId", type: "uint256" },
      { name: "version", type: "uint64" },
      { name: "designHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "price", type: "uint256" },
      { name: "sliceBps", type: "uint16" },
      { name: "quantity", type: "uint256" },
      { name: "pubkey", type: "bytes32" },
      { name: "exists", type: "bool" },
      { name: "openOrders", type: "uint256" },
      { name: "grantId", type: "uint256" },
      { name: "grantBps", type: "uint16" },
      { name: "grantLinked", type: "bool" },
      { name: "cyberSwagBps", type: "uint16" },
      { name: "confirmWindow", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "orders",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "offerId", type: "uint256" },
      { name: "buyer", type: "address" },
      { name: "oracle", type: "address" },
      { name: "quantity", type: "uint256" },
      { name: "escrowAmount", type: "uint256" },
      { name: "slice", type: "uint256" },
      { name: "grantId", type: "uint256" },
      { name: "grantSlice", type: "uint256" },
      { name: "cyberSlice", type: "uint256" },
      { name: "shippingCommitment", type: "bytes32" },
      { name: "deadline", type: "uint64" },
      { name: "open", type: "bool" },
      { name: "stage", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "upfrontBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "minSliceBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "agentsOf",
    stateMutability: "view",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [{ type: "uint256[]" }],
  },
  {
    type: "function",
    name: "createOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "kitId", type: "uint256" },
      { name: "version", type: "uint64" },
      { name: "designHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "price", type: "uint256" },
      { name: "sliceBps", type: "uint16" },
      { name: "quantity", type: "uint256" },
      { name: "pubkey", type: "bytes32" },
      { name: "confirmWindow", type: "uint64" },
      { name: "cyberSwagBps", type: "uint16" },
    ],
    outputs: [{ name: "offerId", type: "uint256" }],
  },
  {
    type: "function",
    name: "updateOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "price", type: "uint256" },
      { name: "sliceBps", type: "uint16" },
      { name: "quantity", type: "uint256" },
      { name: "newContentUri", type: "string" },
      { name: "confirmWindow", type: "uint64" },
      { name: "cyberSwagBps", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setPubkey",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "pubkey", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "linkGrant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "grantId", type: "uint256" },
      { name: "grantBps", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "unlinkGrant",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "linkAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "agentId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "unlinkAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "agentId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setCyberSwagBps",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "cyberSwagBps", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deleteOffer",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "buy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "quantity", type: "uint256" },
      { name: "shippingCommitment", type: "bytes32" },
      { name: "oracle", type: "address" },
      { name: "encryptedShipping", type: "bytes" },
    ],
    outputs: [{ name: "orderId", type: "uint256" }],
  },
  {
    type: "function",
    name: "setOrderStage",
    stateMutability: "nonpayable",
    inputs: [
      { name: "orderId", type: "uint256" },
      { name: "stage", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmReceipt",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmDelivery",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelByFabricator",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelByBuyer",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimAfterDeadline",
    stateMutability: "nonpayable",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setBlacklisted",
    stateMutability: "nonpayable",
    inputs: [
      { name: "fabricator", type: "address" },
      { name: "banned", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "OfferCreated",
    inputs: [
      { name: "offerId", type: "uint256", indexed: true },
      { name: "fabricator", type: "address", indexed: true },
      { name: "kitId", type: "uint256", indexed: false },
      { name: "version", type: "uint64", indexed: false },
      { name: "designHash", type: "bytes32", indexed: false },
      { name: "contentUri", type: "string", indexed: false },
      { name: "price", type: "uint256", indexed: false },
      { name: "sliceBps", type: "uint16", indexed: false },
      { name: "quantity", type: "uint256", indexed: false },
      { name: "confirmWindow", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderPlaced",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "offerId", type: "uint256", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "quantity", type: "uint256", indexed: false },
      { name: "oracle", type: "address", indexed: false },
      { name: "shippingCommitment", type: "bytes32", indexed: false },
      { name: "encryptedShipping", type: "bytes", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderSlices",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "total", type: "uint256", indexed: false },
      { name: "slice", type: "uint256", indexed: false },
      { name: "grantSlice", type: "uint256", indexed: false },
      { name: "cyberSlice", type: "uint256", indexed: false },
      { name: "grantId", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderReleased",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "byOracle", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderRefunded",
    inputs: [{ name: "orderId", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "OrderStageSet",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "stage", type: "uint8", indexed: false },
      { name: "deadline", type: "uint64", indexed: false },
    ],
  },
  { type: "error", name: "NotFabricator", inputs: [] },
  { type: "error", name: "NotCouncil", inputs: [] },
  { type: "error", name: "NoOffer", inputs: [] },
  { type: "error", name: "BadSlice", inputs: [] },
  { type: "error", name: "SoldOut", inputs: [] },
  { type: "error", name: "InvalidQuantity", inputs: [] },
  { type: "error", name: "InvalidStage", inputs: [] },
  { type: "error", name: "AlreadyShipped", inputs: [] },
  { type: "error", name: "HasOpenOrders", inputs: [] },
  { type: "error", name: "OrderClosed", inputs: [] },
  { type: "error", name: "NotBuyer", inputs: [] },
  { type: "error", name: "NotOracle", inputs: [] },
  { type: "error", name: "Banned", inputs: [] },
  { type: "error", name: "NoFunders", inputs: [] },
  { type: "error", name: "SharesExceedEscrow", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "TooEarly", inputs: [] },
  { type: "error", name: "BadWindow", inputs: [] },
  { type: "error", name: "NoAgent", inputs: [] },
  { type: "error", name: "KitMismatch", inputs: [] },
  { type: "error", name: "AlreadyLinked", inputs: [] },
  { type: "error", name: "NotLinked", inputs: [] },
  { type: "error", name: "TooManyAgents", inputs: [] },
] as const;
